name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  repo-token:  # id of input
    description: 'token for repo'
    required: true
    default: 'null shh quiet'
  repo-info:  # id of input
    description: 'info for repo'
    required: true
    default: 'who/what'
outputs:
  repo: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
