# This is a basic workflow to help you get started with Actions
name: Add Project

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
     project-name:
        description: 'a project name'
        required: true
        default: 'Design Stages'
     project-body:
        description: 'a project description'
        required: true
        default: 'This project has design stage columns'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  add-project-job:
    runs-on: ubuntu-latest
    name: A job to add a project
    steps:
    - run: ls -a
        
    - name: Install npm environment
  #    run: npm install
  #  - run: npm list
      
    - run: echo "Git hub context ${{toJson(github.event)}}"
    - name: add project to repo
      id: add-project
      # uses: <owner>/<repo>/<script>@<release/branch>
      uses: michael-motus/helo-js-action/.github/actions/addProject@main
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
        repo-id: ${{github.event.repository.node_id}}
        repo-name: ${{github.event.repository.name}}
        repo-owner: ${{github.event.repository.owner.login}}
