on: #[push]
  workflow_dispatch:
  
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Dump GitHub context
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
    - name: Install npm
      run: npm install
    - name: Hello action step
      id: hello
      uses: michael-motus/helo-js-action@main
      with:
        repo-token: github.token
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.repo }}"
