on: #[push]
  # workflow_dispatch:
  issues:
    types: [labeled]
    # @todo: filter stage labels

jobs:
  move-column-job:
    runs-on: ubuntu-latest
    name: A job to move columns based on labels
    steps:
    - name: Install npm environment
      run: npm install
    - run: echo "Git hub context ${{toJson(github.event)}}"
    - name: set stage column
      id: set-column
      # uses: <owner>/<repo>/<script>@<release/branch>
      uses: michael-motus/helo-js-action/.github/actions/setStageColumn@main
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
        repo-id: ${{github.event.repository.node_id}}
        repo-name: ${{github.event.repository.name}}
        repo-owner: ${{github.event.repository.owner.login}}
        issue-number: ${{github.event.issue.number}}
        new-label: ${{github.event.label.name}}

